package edWood.reader;

import edWood.data.*;

import java.io.IOException;

/**
 * Created by IntelliJ IDEA.
 * User: axel
 * Date: 26.03.12
 * Time: 13:56
 * To change this template use File | Settings | File Templates.
 */
public interface ReaderAdapter {

    public String getDescription();

    public void init(String[] args);

    /**
     * reads life data.
     * @param iterators the life InputIterators.
     * @return itself
     * @throws IOException if any io exception occurs
     */
    public ReaderAdapter readLife(LifeInput input) throws IOException;

    /**
     * reads file data.
     * @param iterators the file InputIterators.
     * @return itself
     * @throws IOException if any io exception occurs
     */
    public ReaderAdapter readPostRunSources(Input[] input) throws IOException;

    /**
     * returns the data generated by readLife() and readPostRunResources()
     * @return the data
     */
    public Object getData();

    /**
     * The object returned by this function will be used to ensure type compatibility
     * with the WriterAdapter before the program is run. It doesn't have to hold any data
     * and only has to hold a class cast.
     * If creating such an object is impossible or overly expensive, null can be returned.
     * @return a dummy data object for testing or null if no test should be performed.
     */
    public Object getDummyData();

    
}
